<?php 
 //WARNING: The contents of this file are auto-generated


// created: 2014-07-17 05:15:19
$dictionary["c1_purchases"]["fields"]["accounts_c1_purchases_1"] = array (
  'name' => 'accounts_c1_purchases_1',
  'type' => 'link',
  'relationship' => 'accounts_c1_purchases_1',
  'source' => 'non-db',
  'module' => 'Accounts',
  'bean_name' => 'Account',
  'vname' => 'LBL_ACCOUNTS_C1_PURCHASES_1_FROM_ACCOUNTS_TITLE',
  'id_name' => 'accounts_c1_purchases_1accounts_ida',
);
$dictionary["c1_purchases"]["fields"]["accounts_c1_purchases_1_name"] = array (
  'name' => 'accounts_c1_purchases_1_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_ACCOUNTS_C1_PURCHASES_1_FROM_ACCOUNTS_TITLE',
  'save' => true,
  'id_name' => 'accounts_c1_purchases_1accounts_ida',
  'link' => 'accounts_c1_purchases_1',
  'table' => 'accounts',
  'module' => 'Accounts',
  'rname' => 'name',
);
$dictionary["c1_purchases"]["fields"]["accounts_c1_purchases_1accounts_ida"] = array (
  'name' => 'accounts_c1_purchases_1accounts_ida',
  'type' => 'link',
  'relationship' => 'accounts_c1_purchases_1',
  'source' => 'non-db',
  'reportable' => false,
  'side' => 'right',
  'vname' => 'LBL_ACCOUNTS_C1_PURCHASES_1_FROM_C1_PURCHASES_TITLE',
);


// created: 2014-07-17 05:11:31
$dictionary["c1_purchases"]["fields"]["c1_purchases_c1_lineitem"] = array (
  'name' => 'c1_purchases_c1_lineitem',
  'type' => 'link',
  'relationship' => 'c1_purchases_c1_lineitem',
  'source' => 'non-db',
  'module' => 'c1_lineitem',
  'bean_name' => 'c1_lineitem',
  'side' => 'right',
  'vname' => 'LBL_C1_PURCHASES_C1_LINEITEM_FROM_C1_LINEITEM_TITLE',
);


// created: 2014-07-17 05:11:31
$dictionary["c1_purchases"]["fields"]["c1_purchases_documents"] = array (
  'name' => 'c1_purchases_documents',
  'type' => 'link',
  'relationship' => 'c1_purchases_documents',
  'source' => 'non-db',
  'module' => 'Documents',
  'bean_name' => 'Document',
  'vname' => 'LBL_C1_PURCHASES_DOCUMENTS_FROM_DOCUMENTS_TITLE',
);


// created: 2014-07-17 05:16:41
$dictionary["c1_purchases"]["fields"]["contacts_c1_purchases_1"] = array (
  'name' => 'contacts_c1_purchases_1',
  'type' => 'link',
  'relationship' => 'contacts_c1_purchases_1',
  'source' => 'non-db',
  'module' => 'Contacts',
  'bean_name' => 'Contact',
  'vname' => 'LBL_CONTACTS_C1_PURCHASES_1_FROM_CONTACTS_TITLE',
  'id_name' => 'contacts_c1_purchases_1contacts_ida',
);
$dictionary["c1_purchases"]["fields"]["contacts_c1_purchases_1_name"] = array (
  'name' => 'contacts_c1_purchases_1_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_CONTACTS_C1_PURCHASES_1_FROM_CONTACTS_TITLE',
  'save' => true,
  'id_name' => 'contacts_c1_purchases_1contacts_ida',
  'link' => 'contacts_c1_purchases_1',
  'table' => 'contacts',
  'module' => 'Contacts',
  'rname' => 'name',
  'db_concat_fields' => 
  array (
    0 => 'first_name',
    1 => 'last_name',
  ),
);
$dictionary["c1_purchases"]["fields"]["contacts_c1_purchases_1contacts_ida"] = array (
  'name' => 'contacts_c1_purchases_1contacts_ida',
  'type' => 'link',
  'relationship' => 'contacts_c1_purchases_1',
  'source' => 'non-db',
  'reportable' => false,
  'side' => 'right',
  'vname' => 'LBL_CONTACTS_C1_PURCHASES_1_FROM_C1_PURCHASES_TITLE',
);



    $dictionary['c1_purchases']['fields']['po_num'] = array (
      'name' => 'po_num',
      'vname' => 'LBL_PO_NUM',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '100',
      'size' => '20',
    );
	$dictionary['c1_purchases']['fields']['po_doc_name'] = array (
      'name' => 'po_doc_name',
      'vname' => 'LBL_PO_DOC_NAME',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '255',
      'size' => '20',
    );
	$dictionary['c1_purchases']['fields']['pi_num'] = array (
      'name' => 'pi_num',
      'vname' => 'LBL_PI_NUM',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '100',
      'size' => '20',
    );
	$dictionary['c1_purchases']['fields']['pi_doc_name'] = array (
      'name' => 'pi_doc_name',
      'vname' => 'LBL_PI_DOC_NAME',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '255',
      'size' => '20',
    );
	$dictionary['c1_purchases']['fields']['system_reference'] = array (
      'name' => 'system_reference',
      'vname' => 'LBL_SYSTEM_REFERENCE',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '100',
      'size' => '20',
    );
	$dictionary['c1_purchases']['fields']['debit_account'] = array (
      'name' => 'debit_account',
      'vname' => 'LBL_DEBIT_ACCOUNT',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '100',
      'size' => '20',
    );
	$dictionary['c1_purchases']['fields']['payment_detail'] = array (
      'name' => 'payment_detail',
      'vname' => 'LBL_PAYMENT_DETAIL',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '100',
      'size' => '20',
    );
	$dictionary['c1_purchases']['fields']['awb_num'] = array (
      'name' => 'awb_num',
      'vname' => 'LBL_AWB_NUM',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '100',
      'size' => '20',
    );
	$dictionary['c1_purchases']['fields']['warehouse_num'] = array (
      'name' => 'warehouse_num',
      'vname' => 'LBL_WAREHOUSE_NUM',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '100',
      'size' => '20',
    );
	$dictionary['c1_purchases']['fields']['tt_doc_name'] = array (
      'name' => 'tt_doc_name',
      'vname' => 'LBL_TT_DOC_NAME',
      'type' => 'varchar',
      'enforced' => '',
      'dependency' => '',
      'required' => false,
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '100',
      'size' => '20',
    );
	// $dictionary['c1_purchases']['fields']['purchase_type'] = array (
      // 'name' => 'purchase_type',
      // 'vname' => 'LBL_PURCHASE_TYPE',
      // 'type' => 'varchar',
      // 'enforced' => '',
      // 'dependency' => '',
      // 'required' => false,
      // 'massupdate' => '0',
      // 'default' => '',
      // 'no_default' => false,
      // 'help' => '',
      // 'importable' => 'true',
      // 'duplicate_merge' => 'disabled',
      // 'duplicate_merge_dom_value' => '0',
      // 'audited' => false,
      // 'reportable' => true,
      // 'unified_search' => false,
      // 'merge_filter' => 'disabled',
      // 'calculated' => false,
      // 'len' => '100',
      // 'size' => '20',
    // );


 // created: 2014-07-17 05:43:19
$dictionary['c1_purchases']['fields']['sales_stage']['options']='purchase_stage_list';
$dictionary['c1_purchases']['fields']['sales_stage']['comments']='Indication of progression towards closure';
$dictionary['c1_purchases']['fields']['sales_stage']['merge_filter']='disabled';

 
?>